# Generated by Django 3.2 on 2023-02-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(default='sdfdsfsdf'),
            preserve_default=False,
        ),
    ]
