# Generated by Django 3.2 on 2023-02-17 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_unique_title_author_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='review_id',
            new_name='review',
        ),
    ]
