# Generated by Django 3.2 on 2023-02-18 09:46

from django.db import migrations, models
import reviews.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[reviews.models.validators.rating_validator]),
        ),
    ]
