# Generated by Django 3.2 on 2023-02-18 09:47

from django.db import migrations, models
import reviews.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[reviews.models.validators.year_validator]),
        ),
    ]
